name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e
            echo "Pulling latest changes..."
            cd /root/najm-course-api
            git pull origin main

            echo "Apply .env"
            export $(cat /etc/.env/najm-course-api/.env | xargs)

            echo "Apply Migrations..."
            sea-orm-cli migrate up
            
            echo "Building the application..."
            cargo build --release

            echo "Stoping the service..."
            sudo systemctl stop najm-course-api.service

            echo "Replacing the service binary..."
            sudo cp target/release/najm-course-api /usr/local/bin/najm-course-api
            sudo chmod +x /usr/local/bin/najm-course-api

            echo "Restarting the service..."
            sudo systemctl restart najm-course-api.service
            
            echo "Deployment complete!"
          EOF
