name: Deploy To VPS

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          set -e

          echo "Deploying to server"

          git config --global --add safe.directory /var/www/najm-course-api

          cd /var/www/najm-course-api

          git pull origin main

          sudo cargo build --release

          sudo systemctl stop najm-course-api

          sudo cp /var/www/najm-course-api/target/release/najm-course-api /opt/najm-course-api/najm-course-api

          sudo chmod +x /opt/najm-course-api/najm-course-api

          sudo systemctl daemon-reload

          sudo systemctl restart najm-course-api

          echo "Deployment completed successfully"

