name: Deploy To VPS

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies and build
      run: |
        cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: target/release/najm-course-api

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          set -e

          echo "Deploying Rust app to server"

          sudo systemctl stop najm-course-api || true

          mkdir -p /home/deploy/najm-course-api/
          mv ~/najm-course-api /home/deploy/najm-course-api/najm-course-api
          chmod +x /home/deploy/najm-course-api/najm-course-api

          sudo chown -R deploy:deploy /home/deploy/najm-course-api

          sudo systemctl daemon-reload
          sudo systemctl restart najm-course-api
