name: Deploy To VPS

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies and build
      run: |
        cargo build --release
        ls -la target/release
        file target/release/najm-course-api

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-artifact
        path: target/release/najm-course-api

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: release-artifact
        path: .

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          set -e

          echo "Deploying to server"

          mv najm-course-api /home/deploy/temp-build/najm-course-api

          sudo systemctl stop najm-course-api || true

          sudo mkdir -p /opt/najm-course-api

          sudo mv /home/deploy/temp-build/najm-course-api /opt/najm-course-api/najm-course-api

          sudo chown deploy:deploy /opt/najm-course-api/najm-course-api
          sudo chmod +x /opt/najm-course-api/najm-course-api

          sudo systemctl daemon-reload

          sudo systemctl restart najm-course-api

          echo "Deployment completed successfully"

